arch: amd64
os: linux
dist:
  - bionic
  - focal
  - precise
  - trusty
  - xenial
language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

install:
  - source <(bash ./test-utils/setup.sh)

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
