default_host: my-remote-site  # optional, if only one host is defined, that one
                              # will be used. Can be overwritten by ASFA_HOST
                              # environment variable.
expire: 3days  # optional, expire all uploads with the given duration by default
verify_via_hash: true  # defaults to true
prefix_length: 32  # optional, defaults to 32, how many hex-digits of the hash
                   # to print
auth:
  # If set, asfa will try to extract configuration parameters set from openSSH.
  # Settings are looked up for the alias of the host entry.
  # Currently, the following settings are read:
  # * private keys
  from_openssh: true  # defaults to false until next minor release
  interactive: true  # defaults to true
  use_agent: true  # defaults to true
  private_key_file: /path/to/private/key/file/in/pem/format  # optional
  private_key_file_password: foobar  # optional, but highly discouraged
                                     # * will be prompted for if interactive is
                                     #   set to true and not given here
                                     # * set explicitly to "" in order to
                                     #   indicate private key without password
hosts:  # dictionary mapping host alias to host settings
        # Each host can also be be defined in an `<alias>.yaml` file in a
        # hosts-subfolder
  my-remote-site:
    hostname: my-hostname.eu:222  # defaults to alias name if unset
                                  # Note: port-suffix will be inferred form
                                  # openSSH and defaults to 22 otherwise
    user: my-remote-user  # defaults to current user if not set
    folder: /var/www/default/asfa  # target folder where to store data,
                                   # needs to be writable
    expire: 1day  # host-specific setting for expiring all uploads
    url: https://my-domain.eu/asfa  # URL that is prefixed when URLs are
                                          # printed, this is of no functional
                                          # relevance right now
    group: www-data  # optional, group to assign to files after upload so that
                     # they are readable by the webserver
    password: foobar  # optional and highly discouraged, password to login to
                      # server, stored in plaintext
    auth:  # optional, overwrites global auth-config, see auth above!
      interactive: false
      private_key_file: /path/to/private/key/in/pem/format
