name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Setup docker for tests
      run: bash test-utils/setup.sh > env.sh
    - name: Run tests
      run: bash -c "source env.sh && cargo test --verbose"

